### ISSUE TITLE
No longer work with python 3.6 (future feature annotations)

### ISSUE THREAD

**Issue by petterreinholdtsen** [unioslo/pybofh#1]
According to https://pypi.org/project/bofh, the library should work with Python::3.6.  But it fail to work because it uses 'from __future__ import annontations', which according to https://stackoverflow.com/questions/70515194/syntaxerror-future-feature-annotations-is-not-defined showed up in Python 3.7.  Perhaps the package description to match reality?

**Comment by petterreinholdtsen** [comment]
This is the error I see:
```
  ERROR: Command errored out with exit status 1:
   command: /root/rpmbuild/BUILD/tsd-project-api-0.6.7/opt/tsd-project-api/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ktoseio0/bofh_18af05e69289443fbca6916fe985401e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ktoseio0/bofh_18af05e69289443fbca6916fe985401e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_p508iiv                                                                                
       cwd: /tmp/pip-install-ktoseio0/bofh_18af05e69289443fbca6916fe985401e/             
  Complete output (24 lines):                                                            
  Traceback (most recent call last):                                                     
    File "<string>", line 1, in <module>                                                 
    File "/tmp/pip-install-ktoseio0/bofh_18af05e69289443fbca6916fe985401e/setup.py", line 186, in <module>
      main()
    File "/tmp/pip-install-ktoseio0/bofh_18af05e69289443fbca6916fe985401e/setup.py", line 170, in main
      'publish': Publish,
    File "/root/rpmbuild/BUILD/tsd-project-api-0.6.7/opt/tsd-project-api/lib64/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/root/rpmbuild/BUILD/tsd-project-api-0.6.7/opt/tsd-project-api/lib64/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
      k: v for k, v in attrs.items()
    File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
      self.finalize_options()
    File "/root/rpmbuild/BUILD/tsd-project-api-0.6.7/opt/tsd-project-api/lib64/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
      ep.load()(self, ep.name, value)
    File "/root/rpmbuild/BUILD/tsd-project-api-0.6.7/opt/tsd-project-api/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
      return self.resolve()
    File "/root/rpmbuild/BUILD/tsd-project-api-0.6.7/opt/tsd-project-api/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/tmp/pip-install-ktoseio0/bofh_18af05e69289443fbca6916fe985401e/.eggs/setuptools_scm-7.1.0-py3.6.egg/setuptools_scm/__init__.py", line 5
      from __future__ import annotations
      ^
  SyntaxError: future feature annotations is not defined
```
